### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by mvayngrib** [tradle/tim#19]
i just enabled the `no-unused-vars` rule in our .eslintrc, and it found ~1k unused vars across our files :)

eslint + [eslint-nibble](https://github.com/IanVS/eslint-nibble) can autofix many linting issues, but it needs to be at least reviewed by eyeball. @pgmemk want to give it a try?

**Comment by pgmemk** [comment]
cleaned up most of the unused vars. Some of them in your sources I was not sure about. But I deleted about 800 unused vars. Thanks :)

**Comment by urbien** [comment]
fixed
